services:

  _defaults:
    autowire: true
    autoconfigure: true

### Map entities
doctrine:
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Geolocation:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/lordsimal/bolt-geolocation-field/src/Entity'
        prefix: 'Bolt\Geolocation'
        alias: Geolocation